# Generated by Django 5.2 on 2025-04-16 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('мебель', 'Мебель'), ('электроника', 'Электроника'), ('книги', 'Книги'), ('спортинвентарь', 'Спортинвентарь')], max_length=30),
        ),
    ]
